In [59]:
import numpy as np

In [60]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [61]:
type(a)

numpy.ndarray

In [62]:
a.dtype

dtype('int32')

In [63]:
a.ndim

1

In [64]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a + b

array([3, 5, 7, 9])

In [65]:
a * b

array([ 2,  6, 12, 20])

In [66]:
a ** b

array([   1,    8,   81, 1024])

In [67]:
a * 0.1

array([0.1, 0.2, 0.3, 0.4])

In [68]:
a *= 2
a

array([2, 4, 6, 8])

In [69]:
x = 0.1 * a
x

array([0.2, 0.4, 0.6, 0.8])

In [70]:
y = np.sin(x)
y

array([0.19866933, 0.38941834, 0.56464247, 0.71735609])

In [71]:
a = np.array([0, 1, 2, 3])
a[0]

0

In [72]:
a[0] = 10
a

array([10,  1,  2,  3])

In [73]:
a.dtype

dtype('int32')

In [74]:
a[0] = 10.6
a

array([10,  1,  2,  3])

In [75]:
a = np.array([
    [0, 1, 2, 3],
    [10, 11, 12, 13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [76]:
a.shape

(2, 4)

In [77]:
a.size

8

In [78]:
a.ndim

2

In [79]:
a[1, 3]

13

In [80]:
a[1, 3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [81]:
a = np.array([10, 11, 12, 13, 14])
a[1:3]

array([11, 12])

In [82]:
a[1:-2]

array([11, 12])

In [83]:
a[-4:3]

array([11, 12])

In [84]:
a[:3]

array([10, 11, 12])

In [85]:
a[-2:]

array([13, 14])

In [86]:
a[::2]

array([10, 12, 14])

In [87]:
a = np.array([[i + 10 * j for i in range(6)] for j in range(6)])
a[0, 3:5]

array([3, 4])

In [88]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [89]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [90]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [91]:
a = np.array([0, 1.0, 2, 3])
a.dtype

dtype('float64')

In [92]:
a.nbytes

32

In [96]:
a = np.array([0, 1.0, 2, 3], dtype='float32')
a.dtype

dtype('float32')

In [97]:
a.nbytes

16

In [98]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [99]:
a.dtype

dtype('float64')

In [100]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [101]:
np.ones((2, 3), dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [102]:
np.zeros(3)

array([0., 0., 0.])

In [103]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [104]:
np.arange(4)

array([0, 1, 2, 3])

In [113]:
np.arange(1.5, 2.1, 0.3)

array([1.5, 1.8, 2.1])

In [116]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
])

a.shape

(2, 3)

In [117]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [119]:
a.T.shape

(3, 2)

In [121]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
])
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [124]:
a.reshape(6, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [125]:
a.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [126]:
v = np.arange(3)
v

array([0, 1, 2])

In [127]:
M = np.arange(9).reshape(3, 3)
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
v * v

array([0, 1, 4])

In [129]:
M * M

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [130]:
v @ v

5

In [131]:
M @ M

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])